// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzjBG7EPn_ftLrBGqfS3cWWWDbOMjWoeA',
    appId: '1:282498333237:web:311a296d0735783a26cf7c',
    messagingSenderId: '282498333237',
    projectId: 'tallerapp-62bfb',
    authDomain: 'tallerapp-62bfb.firebaseapp.com',
    storageBucket: 'tallerapp-62bfb.appspot.com',
    measurementId: 'G-8N49BG5K4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4TdUAZ9IdpdzvBn83TBthpaic8NcfYZI',
    appId: '1:282498333237:android:62e1191c80b25f8426cf7c',
    messagingSenderId: '282498333237',
    projectId: 'tallerapp-62bfb',
    storageBucket: 'tallerapp-62bfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJEByNf3vsOZuzeCMvdBfLtfv9KpiGgKk',
    appId: '1:282498333237:ios:ee2f6a1c6849ba3f26cf7c',
    messagingSenderId: '282498333237',
    projectId: 'tallerapp-62bfb',
    storageBucket: 'tallerapp-62bfb.appspot.com',
    androidClientId: '282498333237-4gmokslelekrdrn837f0729f0sdqbh3r.apps.googleusercontent.com',
    iosClientId: '282498333237-nra0feu8qgpfb0k5t624dqrel3oqsrj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.taller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJEByNf3vsOZuzeCMvdBfLtfv9KpiGgKk',
    appId: '1:282498333237:ios:ee2f6a1c6849ba3f26cf7c',
    messagingSenderId: '282498333237',
    projectId: 'tallerapp-62bfb',
    storageBucket: 'tallerapp-62bfb.appspot.com',
    androidClientId: '282498333237-4gmokslelekrdrn837f0729f0sdqbh3r.apps.googleusercontent.com',
    iosClientId: '282498333237-nra0feu8qgpfb0k5t624dqrel3oqsrj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.taller',
  );
}
